language: node_js
dist: trusty
sauce_connect: true,
before_script:
  - npm install
  - npm install -g grunt
node_js: 8
before_script: 
  - npm install
  - npm run build 
script:
  - grunt && npm run bench
